/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OkapiYorkJNInterface */

#ifndef _Included_OkapiYorkJNInterface
#define _Included_OkapiYorkJNInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OkapiYorkJNInterface
 * Method:    i0
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OkapiYorkJNInterface_i0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     OkapiYorkJNInterface
 * Method:    iinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_OkapiYorkJNInterface_iinit
  (JNIEnv *, jobject);

/*
 * Class:     OkapiYorkJNInterface
 * Method:    iexit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_OkapiYorkJNInterface_iexit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
