/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class relex */

#ifndef _Included_relex
#define _Included_relex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     relex
 * Method:    javainit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_relex_javainit
  (JNIEnv *, jobject);

/*
 * Class:     relex
 * Method:    comm
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_relex_comm
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
